export const locationOptions = ["Afghanistan", "Aichi Prefecture", "Alappuzha", "Algeria", "Amiens", "Andalusia", "Annecy", "Araq", "Arizona", "Baden-Wuerttemberg", "Bahrain", "Barcelona", "Bavaria", "Beijing", "Belgium", "Bern", "Bois-Guillaume", "Bordeaux", "Brest", "California", "Canary Islands", "Castellon", "Castile and Leon", "Chiba Prefecture", "Chongqing", "Croatia", "Dijon", "Egypt", "Fo Tan", "France", "Frankfurt", "Fujian", "Fukuoka Prefecture", "Gansu", "Gifu Prefecture", "Guangxi", "Guilan", "Guizhou", "Hamburg", "Haneda", "Hanoi", "Hebei", "Hechi, Guangxi", "Heilongjiang", "Henan", "Hesse", "Ho Chi Minh City", "Hokkaido", "Hong Kong", "Hubei", "Hunan", "Illinois", "Inner Mongolia", "Innsbruck", "Ishikawa", "Israel", "Japan", "Jiangsu", "Jiangxi", "Jilin", "Johor", "Jonkoping", "Kanagawa", "Kathmandu", "Kerala", "Kowloon", "Kumamoto City", "Kumamoto Prefecture", "Kuwait", "Kwai Chung", "Kwun Tong", "Kyoto", "Langkawi", "Lapland", "Lebanon", "Liaoning", "Lile", "London", "Lyon", "Macau", "Madrid", "Malaysia", "Mallorca", "Manila", "Massachusetts", "Mie", "Montpellier", "NSW", "Nagano Prefecture", "Nagoya City", "Nantes", "Nara Prefecture", "Ngau Chi Wan", "Nice", "Ningxia", "Nortern Ireland", "North Rhine-Westphalia", "Okinawa Prefecture", "Osaka Prefecture", "Paris", "Phillipines", "Preah Sihanouk Province", "Qom", "Queensland", "Rhineland-Palatinate", "Rome", "Sagamihara", "Saint-Mande", "Saitama Prefecture", "Sapporo", "Seoul", "Shaanxi", "Shandong", "Shanghai", "Shanxi", "Shanxi (陕西)", "Shenzhen, Guangdong", "Sichuan", "Singapore", "South Australia", "South Korea", "Sri Lanka", "Strasbourg", "Taiwan", "Tehran", "Tenerife", "Texas", "Thailand", "Thanh Hoa", "Tianjin", "Tokyo", "Toronto", "Tsing Yi", "Tubingen", "Tyumen", "UAE", "UK", "Valencia", "Vancouver", "Victoria", "Vietnam", "Vinh Phuc", "Wakayama Prefecture", "Wales", "Wan Chai", "Washington", "Wisconsin", "Wuhan, Hubei", "Xinjiang", "Yau Ma Tei", "York", "Yunnan", "Zabaikalsky", "Zaragoza", "Zhejiang", "Zhuhai"]

export const countryOptions = [
  "Afghanistan",
  "Algeria",
  "Australia",
  "Austria",
  "Bahrain",
  "Belgium",
  "Cambodia",
  "Canada",
  "China",
  "Croatia",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Hong Kong",
  "India",
  "Iran",
  "Israel",
  "Italy",
  "Japan",
  "Kuwait",
  "Lebanon",
  "Malaysia",
  "Nepal",
  "Phillipines",
  "Russia",
  "Singapore",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "UAE",
  "UK",
  "USA",
  "Vietnam",
];
